#!/bin/sh

# switch python2/python3
PYTH=python3
POSTQEDIR=~/pythonprojects/postqe/postqe

QEXSDDIR=~/pythonprojects/qexsd

# run from directory where this script is
cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
EXAMPLE_DIR=`pwd`

# check whether echo has the -e option
if test "`echo -e`" = "-e" ; then ECHO=echo ; else ECHO="echo -e" ; fi

$ECHO
$ECHO "This example shows how to compute rgb and make a movie representative of the molecular dinamics"

$PYTH $POSTQEDIR/calcRGB.py -eig "EIG/*" -rgb "rgbSingleSpectra"  -movie "movie" 

$ECHO " done"


